### ISSUE TITLE
The video don't  work when export to pdf

### ISSUE THREAD

**Issue by chena1982** [doersino/markdeep-slides#19]
I use chrome 75.0.3770.142 64bit.
I test use the demo.md.html.

**Comment by doersino** [comment]
Yes, Chrome does *not* include videos in exported PDFs. Neither does any other browser, so this is sadly not something I can fix. 🤷‍♂

(Sorry about the late response; I incorrectly assumed GitHub would email me about newly filed issues. Turns out that the relevant "Watch" feature was disabled for me for this repository – no idea why, it's always been enabled for the rest of my repositories. Either way, I've enabled it now.)
