### ISSUE TITLE
Issues with printing

### ISSUE THREAD

**Issue by mindv0rtex** [doersino/markdeep-slides#25]
After the most recent commit, the slides are too zoomed in when trying to print in Chrome. Have you observed this?

**Comment by mindv0rtex** [comment]
Just to be on the safe side, I reverted to the previous version of js and css files and printing is back to normal.

**Comment by doersino** [comment]
Oh boy, that's due to my fix for #23, which I neglected to test throughly. Will have to think of a different approach for dealing with always-visible scroll bars soon.

Your workaround will work just fine until then.

**Comment by doersino** [comment]
Turns out this wasn't a difficult fix, after all – I just had to override the new `--vw` and `--vh` variables in the `@media print` style sheet.

(I'm still unhappy with my fix for #23, so there might be further changes in this area in the future, but I'll be sure to thoroughly test things from now on!)
